site_name: Alejandro Piad-Morffis
site_url: https://apiad.net
repo_url: https://github.com/apiad

remote_branch: master

theme:
    name: material
    features:
        - tabs
        - instant
    palette:
        primary: black
        accent: black

markdown_extensions:
    - codehilite
    - toc:
        permalink: True
    - admonition

nav:
    - Home: index.md
    - Projects: projects.md
    - Essays:
        - About essays: essays/index.md
        - Why I love teaching: essays/teaching.md
        - It's all about team-playing: essays/team-playing.md
    - Tweetstorms:
        - About tweetstorms: tweetstorms/index.md
        - Algorithm Complexity: tweetstorms/theorythursday-algorithm-complexity.md
        - Mary's Room: tweetstorms/philosophyfriday-mary-room.md