site_name: Alejandro Piad-Morffis
site_url: https://apiad.net
repo_url: https://github.com/apiad

theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: black
        accent: black

markdown_extensions:
    - codehilite
    - toc:
        permalink: true
    - admonition

nav:
    - Home: index.md
    - Projects: projects.md
    - Essays:
        - Start here: essays/index.md
        - Why I love teaching: essays/teaching.md
        - It's all about team-playing: essays/team-playing.md
    - Tweetstorms:
        - Start here: tweetstorms/index.md
        - Algorithm Complexity: tweetstorms/theorythursday-algorithm-complexity
